version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    target-branch: "dev"
