import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

// The `docs` content is generated by scripts/sync-docs.mjs from the repo's
// markdown (docs/, README, CHANGELOG, ROADMAP) — see website/README.md.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
