import { useEffect, useState } from "react";
import { api, type Domain, type Destination } from "../api";
import { useToast, CopyButton, Switch, ConfirmDialog, TableSkeleton, EmptyState } from "../ui";
import { Mail, Trash2, Pencil, Check, X } from "lucide-react";

interface Alias {
  id: number;
  domain_id: number;
  local_part: string;
  full_address: string;
  destination: string | null;
  label: string | null;
  active: 0 | 1;
  source: string;
  fwd_count: number;
  blocked_count: number;
  reply_count: number;
  created_at: number;
  last_seen_at: number | null;
  muted_until: number | null;
}

interface DeleteTarget { id: number; full_address: string }

export function Aliases() {
  const { toast } = useToast();
  const [rows, setRows] = useState<Alias[]>([]);
  const [domains, setDomains] = useState<Domain[]>([]);
  const [destinations, setDestinations] = useState<Destination[]>([]);
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ domain_id: 0, local_part: "", destination: "", label: "" });
  const [submitting, setSubmitting] = useState(false);
  const [togglingId, setTogglingId] = useState<number | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null);
  const [maxTotalAliases, setMaxTotalAliases] = useState(-1);
  const [aliasQuotaBufferEnabled, setAliasQuotaBufferEnabled] = useState(true);

  const [editingId, setEditingId] = useState<number | null>(null);
  const [editLabelValue, setEditLabelValue] = useState("");
  const [editDestValue, setEditDestValue] = useState("");
  const [savingId, setSavingId] = useState<number | null>(null);

  async function load() {
    setLoading(true);
    try {
      setRows(await api.aliases(q));
    } catch {
      toast("Failed to load aliases", "error");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    Promise.all([api.domains(), api.destinations(), api.config()]).then(([doms, dests, conf]) => {
      const availableDomains = doms.filter(d => d.is_global === 0 || (d.active === 1 && d.verified_at !== null));
      setDomains(availableDomains);
      setDestinations(dests.filter(d => d.verified_at !== null));
      setForm(f => ({ ...f, domain_id: availableDomains[0]?.id ?? 0 }));
      setMaxTotalAliases(conf.max_total_aliases);
      setAliasQuotaBufferEnabled(conf.alias_quota_buffer_enabled);
    });
  }, []);

  useEffect(() => { load(); }, [q]);

  const selectedDomain = domains.find(d => d.id === form.domain_id);
  const isGlobal = selectedDomain?.is_global === 1;
  const isAutoGenerated = isGlobal && selectedDomain?.allow_custom_aliases !== 1;

  async function create(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    try {
      await api.createAlias({
        domain_id: Number(form.domain_id),
        local_part: isAutoGenerated ? "" : form.local_part,
        destination: form.destination || undefined,
        label: form.label || undefined,
      });
      setForm(f => ({ ...f, local_part: "", destination: "", label: "" }));
      await load();
      toast("Alias created", "success");
    } catch (err: any) {
      toast(err.message || "Failed to create alias", "error");
    } finally {
      setSubmitting(false);
    }
  }

  async function toggleActive(alias: Alias, value: boolean) {
    setTogglingId(alias.id);
    try {
      await api.patchAlias(alias.id, { active: value ? 1 : 0 });
      setRows(prev => prev.map(a => a.id === alias.id ? { ...a, active: value ? 1 : 0 } : a));
      toast(`${alias.local_part} ${value ? "activated" : "deactivated"}`, "success");
    } catch {
      toast("Failed to update alias", "error");
    } finally {
      setTogglingId(null);
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return;
    const target = deleteTarget;
    setDeleteTarget(null);
    try {
      await api.deleteAlias(target.id);
      setRows(prev => prev.filter(a => a.id !== target.id));
      toast(`${target.full_address} deleted`, "success");
    } catch (err: any) {
      console.error("Failed to delete alias:", err);
      toast("Failed to delete alias", "error");
    }
  }

  function startEdit(alias: Alias) {
    setEditingId(alias.id);
    setEditLabelValue(alias.label || "");
    setEditDestValue(alias.destination || "");
  }

  function cancelEdit() {
    setEditingId(null);
  }

  async function saveEdit(alias: Alias) {
    const trimmedLabel = editLabelValue.trim();
    const newLabel = trimmedLabel === "" ? null : trimmedLabel;
    const newDest = editDestValue === "" ? null : editDestValue;
    if (newLabel === alias.label && newDest === alias.destination) {
      cancelEdit();
      return;
    }

    setSavingId(alias.id);
    try {
      const patch: Record<string, unknown> = {};
      if (newLabel !== alias.label) patch.label = newLabel;
      if (newDest !== alias.destination) patch.destination = newDest;
      await api.patchAlias(alias.id, patch);
      setRows(prev => prev.map(a => a.id === alias.id ? { ...a, label: newLabel, destination: newDest } : a));
      toast("Alias updated", "success");
    } catch (err: any) {
      toast(err.message || "Failed to update alias", "error");
    } finally {
      setSavingId(null);
      cancelEdit();
    }
  }

  const isOverQuota = maxTotalAliases >= 0 && rows.length > maxTotalAliases;
  const hardLimit = maxTotalAliases >= 0 ? maxTotalAliases + (aliasQuotaBufferEnabled ? 1 : 0) : -1;
  const isAtHardLimit = hardLimit >= 0 && rows.length >= hardLimit;

  return (
    <div>
      {/* Page header */}
      <div className="page-header">
        <div className="page-title-row">
          <h1 className="page-title">Aliases</h1>
        </div>
        <p className="page-subtitle">
          Email aliases — forward, reply, and block senders without exposing your real inbox.
        </p>
      </div>

      {isOverQuota && (
        <div className="stagger-1" style={{ marginBottom: "24px" }}>
          <div className="banner danger" style={{ borderRadius: "8px", padding: "16px", backgroundColor: "rgba(255, 60, 60, 0.1)", border: "1px solid rgba(255, 60, 60, 0.2)", color: "#ff8b8b" }}>
            <strong style={{ fontSize: "16px", fontWeight: "600", display: "block", marginBottom: "4px" }}>Quota Exceeded ({rows.length} / {maxTotalAliases})</strong>
            <p style={{ margin: "0", fontSize: "14px", lineHeight: "1.5" }}>
              {isAtHardLimit 
                ? `You have reached your absolute hard limit of ${hardLimit} aliases. No new catch-all emails can be received until you delete some aliases.` 
                : `You are over your alias limit. New catch-all aliases have a 1-hour grace period before inbound emails are blocked. Delete old aliases to continue.`}
            </p>
          </div>
        </div>
      )}

      {/* Reply hint callout */}
      <div className="callout stagger-1 card-form-gap">
        <strong>How replies work —</strong>{" "}
        When mail is forwarded, the{" "}
        <code>Reply-To</code>{" "}
        header is set to a unique reverse-alias:{" "}
        <code>
          alias+sender=domain@yourdomain
        </code>
        . Replying from your real inbox routes through SES and arrives as the alias — the sender
        never sees your real address.
      </div>

      {/* Create alias form */}
      <div className="card stagger-2 card-form-gap">
        <div className="card-header">
          <span className="card-title">New Alias {maxTotalAliases >= 0 ? `(${rows.length} / ${maxTotalAliases} used)` : `(${rows.length} used)`}</span>
        </div>
        <form onSubmit={create}>
          <div className="form-strip">
            <div className="field form-field-sm">
              <label className="field-label" htmlFor="al-domain">Domain</label>
              <select
                id="al-domain"
                className="input input-mono"
                value={form.domain_id}
                onChange={e => setForm(f => ({ ...f, domain_id: Number(e.target.value) }))}
                disabled={submitting}
              >
                {domains.map(d => <option key={d.id} value={d.id}>@{d.domain}</option>)}
              </select>
            </div>
            <div className="field form-field-md">
              <label className="field-label" htmlFor="al-local">Local part</label>
              <input
                id="al-local"
                className="input input-mono"
                type="text"
                placeholder={isAutoGenerated ? "<auto-generated>" : "shopping"}
                value={isAutoGenerated ? "" : form.local_part}
                onChange={e => setForm(f => ({ ...f, local_part: e.target.value }))}
                required={!isAutoGenerated}
                disabled={submitting || isAutoGenerated}
                title={isAutoGenerated ? "Global domains automatically generate random alias names" : ""}
              />
            </div>
            <div className="field grow">
              <label className="field-label" htmlFor="al-dest">Destination (optional)</label>
              <select
                id="al-dest"
                className="input input-mono"
                value={form.destination}
                onChange={e => setForm(f => ({ ...f, destination: e.target.value }))}
                disabled={submitting || destinations.length === 0}
              >
                <option value="">{isGlobal ? "-- Global Default --" : "-- Domain Default --"}</option>
                {destinations.map(d => <option key={d.id} value={d.email}>{d.email}</option>)}
              </select>
            </div>
            <div className="field form-field-sm">
              <label className="field-label" htmlFor="al-label">Label</label>
              <input
                id="al-label"
                className="input"
                type="text"
                placeholder="e.g. Amazon"
                value={form.label}
                onChange={e => setForm(f => ({ ...f, label: e.target.value }))}
                disabled={submitting}
              />
            </div>
            <button className="btn btn-primary form-submit" type="submit" disabled={submitting || (!isAutoGenerated && !form.local_part)}>
              {submitting ? "Creating…" : "Create"}
            </button>
          </div>
          {destinations.length === 0 && (
            <div className="form-help">
              You must verify a destination email on the Destinations tab before creating custom aliases.
            </div>
          )}
        </form>
      </div>

      {/* Search */}
      <div className="stagger-3 table-toolbar">
        <input
          className="input table-search"
          type="search"
          placeholder="Search aliases, labels, destinations…"
          value={q}
          onChange={e => setQ(e.target.value)}
        />
      </div>

      {/* Aliases table */}
      <div className="stagger-4">
        <div className="table-wrap table-wrap-stack">
          <table className="dossier dossier-stack">
            <thead>
              <tr>
                <th>Alias</th>
                <th>Destination</th>
                <th>Fwd</th>
                <th>Reply</th>
                <th>Blocked</th>
                <th>Source</th>
                <th>Active</th>
                <th></th>
              </tr>
            </thead>
            {loading ? (
              <TableSkeleton cols={8} rows={6} />
            ) : (
              <tbody>
                {rows.map(a => (
                  <tr key={a.id} style={a.source === "auto_over_quota" ? { backgroundColor: "rgba(255, 60, 60, 0.06)", boxShadow: "inset 0 0 0 1px rgba(255, 60, 60, 0.15)" } : {}}>
                    <td data-label="Alias">
                      <div className="addr-cell addr-stack">
                        <div className="addr-cell">
                          <span className="addr-mono">{a.full_address}</span>
                          <CopyButton text={a.full_address} />
                        </div>
                        {editingId === a.id ? (
                          <input
                            type="text"
                            className="input"
                            value={editLabelValue}
                            onChange={e => setEditLabelValue(e.target.value)}
                            onKeyDown={e => {
                              if (e.key === "Enter") saveEdit(a);
                              else if (e.key === "Escape") cancelEdit();
                            }}
                            placeholder="Label"
                            disabled={savingId === a.id}
                            autoFocus
                          />
                        ) : (
                          a.label && <span className="row-note">{a.label}</span>
                        )}
                      </div>
                    </td>
                    <td data-label="Destination">
                      {editingId === a.id ? (
                        <select
                          className="input"
                          value={editDestValue}
                          onChange={e => setEditDestValue(e.target.value)}
                          disabled={savingId === a.id}
                        >
                          <option value="">{domains.find(d => d.id === a.domain_id)?.is_global === 1 ? "-- Global Default --" : "-- Domain Default --"}</option>
                          {destinations.map(d => (
                            <option key={d.id} value={d.email}>{d.email}</option>
                          ))}
                        </select>
                      ) : a.destination ? (
                        <div className="addr-cell">
                          <span
                            className="addr-mono redact redacted-token redacted-token-sm"
                            title={a.destination}
                          >
                            {a.destination}
                          </span>
                          <CopyButton text={a.destination} />
                        </div>
                      ) : (
                        <span className="row-note muted-italic">
                          {domains.find(d => d.id === a.domain_id)?.is_global === 1 ? "global default" : "domain default"}
                        </span>
                      )}
                    </td>
                    <td data-label="Fwd"><span className="badge-count">{a.fwd_count}</span></td>
                    <td data-label="Reply"><span className="badge-count">{a.reply_count}</span></td>
                    <td data-label="Blocked">
                      <span className="badge-count" style={a.blocked_count > 0 ? { color: "var(--red)", background: "var(--red-dim)" } : {}}>
                        {a.blocked_count}
                      </span>
                    </td>
                    <td data-label="Source">
                      {a.source === "auto_over_quota" ? (
                        <span className="badge" style={{ backgroundColor: "rgba(255, 60, 60, 0.15)", color: "#ff8b8b", border: "1px solid rgba(255, 60, 60, 0.3)" }}>
                          {Date.now() - a.created_at > 3600000 ? "Blocked (Grace Expired)" : "Over Quota (1hr Grace)"}
                        </span>
                      ) : a.muted_until && a.muted_until > Date.now() ? (
                        <span className="badge badge-amber" title={`Muted until ${new Date(a.muted_until).toLocaleString()}`}>
                          Muted
                        </span>
                      ) : (
                        <span className={`badge badge-${a.source === "manual" ? "amber" : "muted"}`}>
                          {a.source}
                        </span>
                      )}
                    </td>
                    <td data-label="Active">
                      <Switch
                        checked={!!a.active}
                        onChange={v => toggleActive(a, v)}
                        disabled={togglingId === a.id}
                        label={a.active ? "Active" : "Inactive"}
                      />
                    </td>
                    <td>
                      <div className="addr-cell">
                        {editingId === a.id ? (
                          <>
                            <button className="btn-icon" onClick={() => saveEdit(a)} disabled={savingId === a.id} title="Save changes">
                              <Check size={16} />
                            </button>
                            <button className="btn-icon" onClick={cancelEdit} disabled={savingId === a.id} title="Cancel">
                              <X size={16} />
                            </button>
                          </>
                        ) : (
                          <>
                            <button className="btn-icon" onClick={() => startEdit(a)} title="Edit alias">
                              <Pencil size={16} />
                            </button>
                            <button
                              className="btn-icon danger"
                              type="button"
                              onClick={() => setDeleteTarget({ id: a.id, full_address: a.full_address })}
                              title="Delete alias"
                            >
                              <Trash2 size={16} />
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            )}
          </table>
          {!loading && rows.length === 0 && (
            <EmptyState
              icon={<Mail size={40} />}
              title={q ? "No aliases match your search" : "No aliases yet"}
              body={q ? "Try a different search term." : "Create an alias above, or send mail to any address at your domain — it auto-creates."}
            />
          )}
        </div>
      </div>

      {/* Confirm delete dialog */}
      {deleteTarget && (
        <ConfirmDialog
          title="Delete alias"
          body={`Permanently delete ${deleteTarget.full_address}? Forwarding to this address will stop immediately.`}
          confirmLabel="Delete alias"
          onConfirm={confirmDelete}
          onCancel={() => setDeleteTarget(null)}
        />
      )}
    </div>
  );
}
