ALTER TABLE users ADD COLUMN active INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN forwarding INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN name TEXT;
ALTER TABLE users ADD COLUMN recovery_token TEXT;
ALTER TABLE users ADD COLUMN recovery_expires_at INTEGER;
